let data2 = {
    "nodes": [{'name': 'Infection,mech_vent'},
    {'name': 'Explicit Sepsis'},
    {'name': 'Infection,organ_dysfunction'},
    {'name': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent'},
    {'name': 'Explicit Sepsis,Infection,mech_vent'},
    {'name': 'Explicit Sepsis,Infection,organ_dysfunction'},
    {'name': 'Infection,organ_dysfunction,mech_vent'}]
   ,
    "links": [
    {'source': 'Infection,organ_dysfunction',
    'target': 'Explicit Sepsis,Infection,organ_dysfunction',
    'value': 177},
    {'source': 'Infection,mech_vent',
        'target': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'value': 54},
    {'source': 'Infection,organ_dysfunction,mech_vent',
        'target': 'Infection,organ_dysfunction',
        'value': 172},
    {'source': 'Infection,organ_dysfunction,mech_vent',
        'target': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'value': 92},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction',
        'target': 'Infection,organ_dysfunction,mech_vent',
        'value': 25},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'target': 'Explicit Sepsis,Infection,organ_dysfunction',
        'value': 41},
    {'source': 'Infection,organ_dysfunction',
        'target': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'value': 133},
    {'source': 'Infection,mech_vent',
        'target': 'Infection,organ_dysfunction',
        'value': 97},
    {'source': 'Infection,organ_dysfunction,mech_vent',
        'target': 'Infection,mech_vent',
        'value': 85},
    {'source': 'Infection,mech_vent',
        'target': 'Infection,organ_dysfunction,mech_vent',
        'value': 90},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction',
        'target': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'value': 41},
    {'source': 'Infection,organ_dysfunction,mech_vent',
        'target': 'Explicit Sepsis,Infection,organ_dysfunction',
        'value': 41},
    {'source': 'Infection,organ_dysfunction',
        'target': 'Infection,organ_dysfunction,mech_vent',
        'value': 152},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'target': 'Infection,organ_dysfunction,mech_vent',
        'value': 51},
    {'source': 'Infection,mech_vent',
        'target': 'Explicit Sepsis,Infection,organ_dysfunction',
        'value': 26},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction',
        'target': 'Infection,mech_vent',
        'value': 15},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction',
        'target': 'Infection,organ_dysfunction',
        'value': 128},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'target': 'Infection,organ_dysfunction',
        'value': 69},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'target': 'Explicit Sepsis,Infection,mech_vent',
        'value': 8},
    {'source': 'Infection,organ_dysfunction',
        'target': 'Infection,mech_vent',
        'value': 79},
    {'source': 'Infection,organ_dysfunction',
        'target': 'Explicit Sepsis,Infection,mech_vent',
        'value': 5},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'target': 'Infection,mech_vent',
        'value': 28},
    {'source': 'Explicit Sepsis,Infection,mech_vent',
        'target': 'Infection,mech_vent',
        'value': 6},
    {'source': 'Infection,organ_dysfunction',
        'target': 'Explicit Sepsis',
        'value': 7},
    {'source': 'Explicit Sepsis,Infection,mech_vent',
        'target': 'Infection,organ_dysfunction,mech_vent',
        'value': 9},
    {'source': 'Infection,organ_dysfunction,mech_vent',
        'target': 'Explicit Sepsis,Infection,mech_vent',
        'value': 10},
    {'source': 'Explicit Sepsis,Infection,mech_vent',
        'target': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'value': 8},
    {'source': 'Infection,mech_vent',
        'target': 'Explicit Sepsis,Infection,mech_vent',
        'value': 8},
    {'source': 'Explicit Sepsis,Infection,mech_vent',
        'target': 'Explicit Sepsis,Infection,organ_dysfunction',
        'value': 1},
    {'source': 'Explicit Sepsis,Infection,mech_vent',
        'target': 'Infection,organ_dysfunction',
        'value': 11},
    {'source': 'Infection,organ_dysfunction,mech_vent',
        'target': 'Explicit Sepsis',
        'value': 4},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction',
        'target': 'Explicit Sepsis,Infection,mech_vent',
        'value': 6},
    {'source': 'Explicit Sepsis',
        'target': 'Infection,organ_dysfunction',
        'value': 7},
    {'source': 'Explicit Sepsis', 'target': 'Infection,mech_vent', 'value': 1},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction',
        'target': 'Explicit Sepsis',
        'value': 4},
    {'source': 'Infection,mech_vent', 'target': 'Explicit Sepsis', 'value': 2},
    {'source': 'Explicit Sepsis',
        'target': 'Explicit Sepsis,Infection,organ_dysfunction',
        'value': 1},
    {'source': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'target': 'Explicit Sepsis',
        'value': 2},
    {'source': 'Explicit Sepsis',
        'target': 'Explicit Sepsis,Infection,organ_dysfunction,mech_vent',
        'value': 2},
    {'source': 'Explicit Sepsis',
        'target': 'Infection,organ_dysfunction,mech_vent',
        'value': 1}
    ]
  };
  
  