-- ------------------------------------------------------------------
-- Title: Quick Sequential Organ Failure Assessment (dailyqsofa)
-- This query extracts the quick sequential organ failure assessment.
-- This score was a recent revision of SOFA, aiming to detect patients at risk of sepsis.
-- The score is calculated on the first day of each ICU patients' stay - though needn't be.
-- ------------------------------------------------------------------

-- Reference for dailyqsofa:
--    Singer M, et al. The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3)
--    Seymour CW, et al. Assessment of Clinical Criteria for Sepsis: For the Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3)

-- Variables used in dailyqsofa:
--  GCS, respiratory rate, systolic blood pressure

-- The following views required to run this query:
--  1) gcsdaily - generated by gcs-first-day.sql
--  2) vitalsdaily - generated by vitals-first-day.sql

-- Note:
--  The score is calculated for *all* ICU patients, with the assumption that the user will subselect appropriate ICUSTAY_IDs.
--  For example, the score is calculated for neonates, but it is likely inappropriate to actually use the score values for these patients.

DROP MATERIALIZED VIEW IF EXISTS dailyqsofa CASCADE;
CREATE MATERIALIZED VIEW dailyqsofa AS
with scorecomp as
(
select ie.icustay_id
  , ie.charttime_by_day
  , v.SysBP_Min
  , v.RespRate_max
  , gcs.MinGCS
from (
    select ie.icustay_id, date_trunc('day', ce.charttime) as charttime_by_day
    from icustays ie
    left join chartevents ce 
    on ie.subject_id = ce.subject_id and ie.hadm_id = ce.hadm_id and ie.icustay_id = ce.icustay_id
) ie
left join vitalsdaily v
  on ie.icustay_id = v.icustay_id and ie.charttime_by_day = v.charttime_by_day
left join gcsdaily gcs
  on ie.icustay_id = gcs.icustay_id and ie.charttime_by_day = v.charttime_by_day
)
, scorecalc as
(
  -- Calculate the final score
  -- note that if the underlying data is missing, the component is null
  -- eventually these are treated as 0 (normal), but knowing when data is missing is useful for debugging
  select icustay_id
  , charttime_by_day
  , case
      when SysBP_Min is null then null
      when SysBP_Min   <= 100 then 1
      else 0 end
    as SysBP_score
  , case
      when MinGCS is null then null
      when MinGCS   <= 13 then 1
      else 0 end
    as GCS_score
  , case
      when RespRate_max is null then null
      when RespRate_max   >= 22 then 1
      else 0 end
    as RespRate_score
  from scorecomp
)
select ie.subject_id, ie.hadm_id, ie.icustay_id, ie.charttime_by_day
, coalesce(SysBP_score,0)
 + coalesce(GCS_score,0)
 + coalesce(RespRate_score,0)
 as dailyqsofa
, SysBP_score
, GCS_score
, RespRate_score
from (
    select ie.subject_id, ie.hadm_id, ie.icustay_id, date_trunc('day', ce.charttime) as charttime_by_day
    from icustays ie
    left join chartevents ce 
    on ie.subject_id = ce.subject_id and ie.hadm_id = ce.hadm_id and ie.icustay_id = ce.icustay_id
) ie
left join scorecalc s
  on ie.icustay_id = s.icustay_id and ie.charttime_by_day = s.charttime_by_day
order by ie.icustay_id, charttime_by_day;

